### ISSUE TITLE
v1 beta improvement checklist

### ISSUE THREAD

**Issue by blizzardengle** [caboodle-tech/lecture#1]
Tasks that need to be looked into before a production version 1 can be officially declared:
- [ ] Documentation for repo (README)
- [ ] HLJSL (code samples) are not always loading on mobile. Possible race condition or timeout?
- [ ] Mobile needs some kind of control menu:
    - [ ] Toggle theme between light and dark.
    - [ ] Toggle presentation fullscreen for easier viewing.
- [ ] Add `archiver` to the repo so a downloadable zip can be auto built.
    - [ ]  Add download link into demo website.
- [ ] Add alternative demo(s) that demonstrates embedded presentations.

**Comment by blizzardengle** [comment]
HLJSL code issue seems to be cause by the code element not being found when the web worker responds with the highlighted code. How is that possible? The `data-hljsl-id` attribute is added before the call to the web worker. More research needed.
